routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::delete('/license_request', 'LicenseRequestController@clear')->name('license_request.clear');
Route::get('tickets.pending', 'TicketController@pending')->name('tickets.pending');
Route::get('tickets.approved', 'TicketController@approved')->name('tickets.approved');
Route::get('tickets.declined', 'TicketController@declined')->name('tickets.declined');
Route::get('tickets.completed', 'TicketController@completed')->name('tickets.completed');
Route::get('tickets.recent', 'TicketController@recent')->name('tickets.recent');

Route::get('tickets/user/{id}', 'TicketController@user')->name('tickets.user');


Route::resources([

	'ips' => 'IpController',
	'types' => 'TypeController',
	'ip_assets' => 'IpAssetsController',
	'ip_licenses' => 'IpLicenseController',
	'license_request' => 'LicenseRequestController',
	'tickets' => 'TicketController'
]);

app/Ip.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ip extends Model
{
    //
    use SoftDeletes;
	//make sure use SoftDeletes is first/topmost here
	//so it can be used for the whole model

    protected $fillable = ["name", "term", "protection_start", "description", "works_covered"];

    /* Get the Ip Assets that Belong to the IP Category */
    //laravel relationship one-to-many
    public function ip_assets()
    {
    	return $this->hasMany('App\IpAssets');
    }
}

app/Http/Controllers/IpController.php
<?php

namespace App\Http\Controllers;

use App\Ip;
use App\IpAssets;
use Illuminate\Http\Request;
use Auth;
use App\User;

class IpController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $ips = Ip::all();
        //put all in Ip in $ips

        // dd($ips);

        return view('ips.index')
                ->with('ips', $ips);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
       $user = Auth::user();

       if($user->id == 1 ){

         return view('ips.create');

        }else{

                $ips = Ip::all();

                return view('ips.index')
                    ->with('ips', $ips)
                    ->with('alert', 'Unauthorized to access page.');

        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $validatedData = $request->validate([

            'name' => 'required|unique:ips,name',
                      //unique to ips table, column name
            'term' => 'required',
            'protection_start' => 'required',
            'description' => 'required',
            'works_covered' => 'required'
        ]);

        $ip = new Ip($validatedData);
        $ip->save();

        return redirect(route('ips.index'))
                 ->with('message', "IP Category {$ip->name} is added successfully.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ip  $ip
     * @return \Illuminate\Http\Response
     */
    public function show(Ip $ip)
    {
        //
        return view('ips.show')->with('ip', $ip);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ip  $ip
     * @return \Illuminate\Http\Response
     */
    public function edit(Ip $ip)
    {

        $user = Auth::user();

       if($user->id == 1 ){

            return view('ips.edit')->with('ip', $ip);

        }else{

                $ips = Ip::all();

                return view('ips.index')
                    ->with('ips', $ips)
                    ->with('alert', 'Unauthorized to access page.');

        }
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ip  $ip
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ip $ip)
    {
        $validatedData = $request->validate([

            'name' => 'required|unique:ips,name',
                      //unique to ips table, column name
            'term' => 'required',
            'protection_start' => 'required',
            'description' => 'required',
            'works_covered' => 'required'
        ]);

        $ip->update($validatedData);
        $ip->save();

        return redirect(route('ips.show', $ip->id))
                 ->with('message', "IP Category is updated successfully.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ip  $ip
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ip $ip)
    {

        $user = Auth::user();

       if($user->id == 1 ){

            $ip_assets = IpAssets::all()->where('ip_id', $ip->id);

            if(count($ip_assets) > 0){

                return redirect(route('ips.index'))
                    ->with('message', "Cannot delete IP Category with existing IP Assets. Delete IP Assets first.")
                    ->with('alert', 'info');

            }else{

                $ip->delete();
                return redirect(route('ips.index'))
                        ->with('message', "IP Category {$ip->name} has been deleted.")
                        ->with('alert', 'warning');

            }


        }else{

            $ips = Ip::all();

                return view('ips.index')
                    ->with('ips', $ips)
                    ->with('alert', 'Unauthorized to access page.');

        }
        

    }
}

resources/views/ips/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Create New IP Category
				</h1>
			</div>
		</div>

		{{-- Displaying The Validation Errors --}}
		@if ($errors->any())
		    <div class="alert alert-danger">
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </div>
		@endif
	

		{{-- start form section --}}
		<div class="row">
			<div class="col-12 col-sm-6 mx-auto">
				<form action="{{ route('ips.store') }}" method="post">
					@csrf
					<label for="name">Category name:</label>
					<input type="text" name="name" id="name" class="form-control form-control-sm autofocus">
					<label for="term">Protection Term:</label>
					<input type="text" name="term" id="term" class="form-control form-control-sm autofocus">
					<label for="protection_start">Protection start:</label>
					<input type="text" name="protection_start" id="protection_start" class="form-control form-control-sm autofocus">
					<label for="description">Description:</label>
					<input type="text" name="description" id="description" class="form-control form-control-sm autofocus">
					<label for="works_covered">Works Covered:</label>
					<input type="text" name="works_covered" id="works_covered" class="form-control form-control-sm autofocus">
					<button class="btn btn-sm btn-primary mt-1">Create IP Category</button>	
				</form>
			</div>
		</div>
		{{-- end form section --}}

	</div>

@endsection

resources/views/ips/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Edit IP Category
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-12 col-md-6 mx-auto">
				{{-- start form --}}
				<form action="{{ route('ips.update', $ip->id) }}" method="post">
					@method('PUT')
					@csrf

					<label for="name">IP Category Name:</label>
					<input 
						id="name" 
						type="text" 
						class="form-control 
								@error('name') is-invalid @enderror" 
						name="name" 
						value="{{ $ip->name }}" 
						required 
						autocomplete="name" 
						autofocus
					>

                    @error('name')
                        <span class="invalid-feedback d-block" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror

                    <label for="term">Protection Term:</label>
					<input 
						id="term" 
						type="text" 
						class="form-control 
								@error('term') is-invalid @enderror" 
						name="term" 
						value="{{ $ip->term }}" 
						required 
						autocomplete="term" 
						autofocus
					>
                    @error('term')
                        <span class="invalid-feedback d-block" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror

                    <label for="protection_start">Protection Start:</label>
					<input 
						id="protection_start" 
						type="text" 
						class="form-control 
								@error('protection_start') is-invalid @enderror" 
						name="protection_start" 
						value="{{ $ip->protection_start }}" 
						required 
						autocomplete="protection_start" 
						autofocus
					>
                    @error('protection_start')
                        <span class="invalid-feedback d-block" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror


                    <label for="description">Description:</label>
					<input 
						id="description" 
						type="text" 
						class="form-control 
								@error('description') is-invalid @enderror" 
						name="description" 
						value="{{ $ip->description }}" 
						required 
						autocomplete="description" 
						autofocus
					>
                    @error('description')
                        <span class="invalid-feedback d-block" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror

                    <label for="works_covered">Works Covered:</label>
					<input 
						id="works_covered" 
						type="text" 
						class="form-control 
								@error('works_covered') is-invalid @enderror" 
						name="works_covered" 
						value="{{ $ip->works_covered }}" 
						required 
						autocomplete="works_covered" 
						autofocus
					>
                    @error('works_covered')
                        <span class="invalid-feedback d-block" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror

					<button class="btn btn-sm btn-warning mt-1">Edit</button>
				</form>
				{{-- start form --}}
			</div>
				}
		</div>
	</div>


@endsection

resources/views/ips/index.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		{{-- header start --}}
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Intellectual Property Categories
				</h1>
			</div>
		</div>
		{{-- header end --}}

		{{-- alert-message --}}
		@includeWhen(Session::has('message'),'partials.alert') 

		{{-- ip list start --}}
		<div class="row">
			@foreach($ips as $ip)
				
				<div class="col-12 col-sm-6 col-md-6 col-lg-6 mx-auto">
				{{-- card start --}}
					@include('ips.partials.card', ['index' => false])
				{{-- card end --}}
				</div>
				
			@endforeach
			
		</div>
		{{-- ip list end--}}
	</div>


@endsection

resources/views/ips/show.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					View Intellectual Property Category
				</h1>
			</div>
		</div>

		{{-- start alert --}}
		@includeWhen(Session::has('message'), 'partials.alert')

		<div class="row">
			<div class="col-12 col-sm-6 col-md-8 mx-auto">
				@include('ips.partials.card', ['view' => false])
			</div>
		</div>
	</div>

@endsection